onTrax-master/onTrax/Areas/Admin/Controllers/DataController.cs
// ***********************************************************************
// Assembly         : onTrax
// Created          : 04-05-2018
//
// Last Modified On : 04-19-2018
// ***********************************************************************
// <summary></summary>
// ***********************************************************************
using onTrax.DAL;
using onTrax.Models;
using onTrax.Utilities;
using onTrax.ViewModels;
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;


/// <summary>
/// The Controllers namespace.
/// </summary>
namespace onTrax.Areas.Admin.Controllers
{
    /// <summary>
    /// Class DataController.
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class DataController : Controller
    {
        /// <summary>
        /// The database
        /// </summary>
        private DAL.AppDbContext db = new AppDbContext();


        /// <summary>
        /// GET: Admin/Data
        /// Data Management Index
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// GET: /Admin/Data/Edit
        /// Search functionality based on user criteria
        /// </summary>
        /// <param name="page">The page.</param>
        /// <param name="Date">The date.</param>
        /// <param name="EmployeeID">The employee identifier.</param>
        /// <param name="ProcessID">The process identifier.</param>
        /// <param name="ProductID">The product identifier.</param>
        /// <param name="BatchID">The batch identifier.</param>
        /// <param name="IssueID">The issue identifier.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Edit(int? page, String Date = null, Int32 EmployeeID = 0, Int32 ProcessID = 0, Int32 ProductID = 0, Int32 BatchID = 0, Int32 IssueID = 0)
        {
            // We will pass through an instance of ManageViewModel
            var model = new EditDataViewModel();

            // Create an instance of the Data utility
            var Data = new Data();

            // Populate model with appropriate Data Utility for each property
            model.ProductionList = Data.GetProductions();
            model.EmployeeList = Data.GetActiveEmployees();
            model.ProductList = Data.GetActiveProducts();
            model.ProcessList = Data.GetActiveProcesses();
            model.IssueList = Data.GetActiveIssues();
            model.BatchList = Data.GetActiveBatches();

            // Filter model based on earch criteria
            if(model.ProductionList != null && model.ProductionList.Where(x => x != null).Count() > 0)
            {
				// Search by date from date picker UI element
                if (Date != null && Date != "")
                {
                    var date = Convert.ToDateTime(Date);
                    model.ProductionList = model.ProductionList.Where(x => x.StartTime.Date == date.Date).ToList();
                    model.Date = date.ToString("yyyy-MM-dd");
                }
                // Search by Employee
                if (EmployeeID != 0)
                {
                    model.ProductionList = model.ProductionList.Where(x => x.Employee.EmployeeID == EmployeeID).ToList();
                    model.EmployeeID = EmployeeID;
                }

                // Search by Process
                if (ProcessID != 0)
                {
                    model.ProductionList = model.ProductionList.Where(x => x.Process.ProcessID == ProcessID).ToList();
                    model.ProcessID = ProcessID;
                }


                // Search by Product
                if (ProductID != 0)
                {
                    model.ProductionList = model.ProductionList.Where(x => x.Product.ProductID == ProductID).ToList();
                    model.ProductID = ProductID;
                }

                // Search by Batch
                if (BatchID != 0)
                {
                    model.ProductionList = model.ProductionList.Where(x => x.Batch.BatchID == BatchID).ToList();
                    model.BatchID = BatchID;
                }


                // Search by Issue
                if (IssueID != 0)
                {
                    model.ProductionList = model.ProductionList.Where(x => x.Issues.Any(i => i.IssueID == IssueID)).ToList();
                    model.IssueID = IssueID;
                }
				
				// Set pagination settings 
                model.PageSize = 25;
                model.PageNumber = (page ?? 1);
            }
            // Return model to view
            return View(model);
        }

        /// <summary>
        /// GET: Admin/Data/Log
        /// Log manual Production
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Log()
        {
			// Create an instance of the Data utility to get active objects and add them to view mdoel
            var data = new Data();
			// We will pass through an instance of the view model
            var model = new LogDataViewModel();
			
			// Add active objects to view model 
            model.EmployeeList = data.GetActiveEmployees();
            model.IssueList = data.GetActiveIssues();
            model.ProductList = data.GetActiveProducts();
            model.ProcessList = data.GetActiveProcesses();
            model.BatchList = data.GetActiveBatches();

            return View(model);
        }

        /// <summary>
        /// POST: Admin/Data/Log
        /// Log manual Production
        /// </summary>
        /// <param name="Model">The model.</param>
        /// <returns>ActionResult.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Log(LogDataViewModel Model)
        {
			// Create an instance of the data utility 
            var d = new Data();

            
            if (Model.StartTime == null || Model.StartTime == "" || Model.StartTime.Count() != 10 || Model.StartTime.Length != 10)
            {

                TempData["Error"] = "Please enter a valid Date.";
                Model.EmployeeList = d.GetActiveEmployees();
                Model.ProductList = d.GetActiveProducts();
                Model.ProcessList = d.GetActiveProcesses();
                Model.BatchList = d.GetActiveBatches();
                Model.IssueList = d.GetActiveIssues();

                Model.SelectedIssues = Model.SelectedIssues;



                return View(Model);
            }
            

            if (!ModelState.IsValid)
            {
                // Production log entry was invalid
                // Kick them back to the view and try again
				// But we have to rebuild the view model first 
                Model.EmployeeList = d.GetActiveEmployees();
                Model.ProductList = d.GetActiveProducts();
                Model.ProcessList = d.GetActiveProcesses();
                Model.BatchList = d.GetActiveBatches();
                Model.IssueList = d.GetActiveIssues();

                Model.SelectedIssues = Model.SelectedIssues;



                return View(Model);
            }

            // If we find that production indeed exists
            if (Model != null)
            {
				// Initialize a new Production object 
                var production = new Production();

                // Grab each property based on the selected value and add it to the new Production object
                production.Employee = db.Employees.Find(Model.EmployeeID);
                production.Product = db.Products.Find(Model.ProductID);
                production.Process = db.Processes.Find(Model.ProcessID);
                production.Batch = db.Batches.Find(Model.BatchID);

                production.Quantity = Model.Quantity;

                // Duration from manual logging is in HOURS
                // Measures are calcualted as MINUTES
                production.Duration = Model.Duration * 60;

				// Convert user-entered times to DateTimes for model and DB 
                production.StartTime = Convert.ToDateTime(Model.StartTime);
				// DateRecorded is only not null if an Admin enters the production manually 
                production.DateRecorded = Model.DateRecorded;
                production.EndTime = Convert.ToDateTime(Model.StartTime);

                // If any issue is selected
                if (Model.SelectedIssues != null && Model.SelectedIssues.Count() > 0)
                {
                    // Insert a list of Issues as the production Issues where the ID is found within the Issues array
                    production.Issues = db.Issues.Where(x => Model.SelectedIssues.Contains(x.IssueID.ToString())).ToList();
                }

                System.Diagnostics.Debug.WriteLine("**********************************");
                System.Diagnostics.Debug.WriteLine(Model.StartTime + " " + Model.StartTime.Length + " " + Model.StartTime.Count());
                System.Diagnostics.Debug.WriteLine("**********************************");

                db.Productions.Add(production);
                db.SaveChanges();
                var ReturnModel = new LogDataViewModel();
				// Inform the user that their data was successfully entered 
                TempData["Success"] = "Production Logged";

                // Rebuild the view model and send them back to the update view 
                ReturnModel.EmployeeList = d.GetActiveEmployees();
                ReturnModel.ProductList = d.GetActiveProducts();
                ReturnModel.ProcessList = d.GetActiveProcesses();
                ReturnModel.BatchList = d.GetActiveBatches();
                ReturnModel.IssueList = d.GetActiveIssues();

                return View(ReturnModel);
            }

            // Fillout the lists if we need to return to the update view
            Model.EmployeeList = d.GetActiveEmployees();

onTrax-master/onTrax/Areas/Admin/Views/Data/Edit.cshtml
@model onTrax.ViewModels.EditDataViewModel
@using PagedList.Mvc;

@{
    ViewBag.Title = "Edit Production Data";
}

@* Display Search Form *@
@using (Html.BeginForm("Edit", "Data", FormMethod.Get, new { @class = "" }))
{
    <div class="container" id="SearchContainer">
        <div class="row">
            <div class="col-2 pl-0 m-auto"><input type="Date" id="Date" name="Date" value="@Model.Date" class="form-control"></div>
            @* Show Dropdowns if they exists*@

            @if (Model.EmployeeList != null && Model.EmployeeList.Where(x => x != null).Count() > 0)
            {
                <div class="col-2 m-auto">@Html.DropDownList("EmployeeID", new SelectList(Model.EmployeeList, "EmployeeID", "EmployeeName"), "Employee", new { @class = "form-control col-12" })</div>
            }
            @if (Model.ProcessList != null && Model.ProcessList.Where(x => x != null).Count() > 0)
            {
                <div class="col-2 pl-0 m-auto">@Html.DropDownList("ProcessID", new SelectList(Model.ProcessList, "ProcessID", "ProcessName"), "Process", new { @class = "form-control col-12" })</div>
            }
            @if (Model.ProductList != null && Model.ProductList.Where(x => x != null).Count() > 0)
            {
                <div class="col-2 pl-0 m-auto">@Html.DropDownList("ProductID", new SelectList(Model.ProductList, "ProductID", "ProductName"), "Product", new { @class = "form-control col-12" })</div>
            }
            @if (Model.IssueList != null && Model.IssueList.Where(x => x != null).Count() > 0)
            {
                <div class="col-1 pl-0 m-auto">@Html.DropDownList("IssueID", new SelectList(Model.IssueList, "IssueID", "IssueName"), "Issue", new { @class = "form-control col-12" })</div>
            }

            @if (Model.BatchList != null && Model.BatchList.Where(x => x != null).Count() > 0)
            {
                <div class="col-1 pl-0 m-auto">@Html.DropDownList("BatchID", new SelectList(Model.BatchList, "BatchID", "BatchName"), "Batch", new { @class = "form-control col-12" })</div>
            }
            
            
            
            
            <div class="col-2 pl-0 "><input type="submit" value="Search" class="btn btn-primary btn col-12" /></div>
        </div>
    </div>
}


@* 
    Display Search Results
    If no search defined, display all results    
*@
<table id="ProductionTable" class="table mt-2">
    <thead>
        <tr>
            <th>Date</th>
            <th>Name</th>
            <th>Process</th>
            <th>Product</th>
            <th>Issue</th>
            <th>Batch #</th>
            <th>Start</th>
            <th>Stop</th>
            <th>Duration (min)</th>
            <th>Quantity</th>
            <th>Delete</th>
            <th>Update</th>
        </tr>
    </thead>
    <tbody>
        @* Display production results if they exists *@
        @if (Model.PagedProductionList != null && Model.PagedProductionList.Where(x => x != null).Count() > 0)
        {
            foreach (var item in Model.PagedProductionList.Where(x => x !=null))
             {
                <tr>
                    <td>@item.StartTime.ToString("MM/dd/yyyy")</td>
                    <td >@item.Employee.EmployeeName</td>
                    <td >@item.Process.ProcessName</td>
                    <td >@item.Product.ProductName</td>
                    @* Display all issues seperated by a comma *@
                    <td>@String.Join(", ", item.Issues.Select(x => x.IssueName))</td>
                    <td >@item.Batch.BatchName</td>
                    <td>@item.StartTime.ToString("hh:mm")</td>
                    <td>@item.EndTime.ToString("hh:mm")</td>
                    <td >@item.Duration</td>
                    <td >@item.Quantity</td>
                    <td>
                        @Html.ActionLink(" ", "Delete", "Data", new { id = item.ProductionID }, new { @class = "col m-auto glyphicon glyphicon-trash", onclick = "return confirm('Are you sure want to delete this production record?');" })
                        @*<button onClick="confirmDelete()" class="col m-auto glyphicon glyphicon-trash" id="item.ProductionID"></button>*@
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Update", "Data", new { id = item.ProductionID }, new { @class = "col m-auto glyphicon glyphicon-pencil" })
                    </td>
                </tr>
            }

        }
        else
        {
            @** We didn't find anything to display **@ 
            <tr>
                <td colspan="12">
                    <span> No records found </span>
                </td>
            </tr>
            
        }

    </tbody>
</table>
        @* Display page navigation if production records exist *@

        @if (Model.PagedProductionList != null && Model.PagedProductionList.Where(x => x != null).Count() > 0)
        {
            <div>
            Page @(Model.PagedProductionList.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PagedProductionList.PageCount
    
            @Html.PagedListPager(Model.PagedProductionList, page => Url.Action("Edit",
            new { page, EmployeeID = Model.EmployeeID, ProcessID = Model.ProcessID, ProductID = Model.ProductID, BatchID = Model.BatchID, IssueID = Model.IssueID, Date = Model.Date}), new PagedListRenderOptions()
            {
                FunctionToTransformEachPageLink = (liTag,aTag) => { aTag.Attributes.Add("class='page-link'", aTag.InnerHtml); liTag.InnerHtml = aTag.ToString(); return liTag; },
                ContainerDivClasses = new List<string> { "Page", "navigation" },
                LiElementClasses = new List<string> { "page-item"}
            })
            </div>
        }

onTrax-master/onTrax/Areas/Admin/Views/Data/Index.cshtml
@{

    ViewBag.Title = "Data Management";
}

        <div class="m-auto text-center" >
            <span class="glyphicon glyphicon-folder-open" aria-hidden="true" style="font-size:200px;"></span>
        </div>


        <div class="row m-2 text-center">
            <div class="col-12 m-auto">
                @Html.ActionLink("Log Production Data", "Log", "Data", null, new { @class = "btn btn-primary btn-lg col-3 m-auto" })

                @Html.ActionLink("Edit Production Data", "Edit", "Data", null, new { @class = "btn btn-success btn-lg col-3 m-auto" })
            </div>
        </div>

onTrax-master/onTrax/Areas/Admin/Views/Data/Log.cshtml
@model onTrax.ViewModels.LogDataViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 style="color:red">Log Production</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">
        <div class="row form-group">
            <div class="col">
                @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    <input type="Date" id="StartTime" name="StartTime" value="@DateTime.Today.ToString("yyyy-MM-dd")" class="form-control">
                </div>
            </div>
            
            <div class="col">
                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @value = "1" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @value="1" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                @Html.LabelFor(model => model.EmployeeList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.EmployeeID, new SelectList(Model.EmployeeList, "EmployeeID", "EmployeeName", "Select Employee"))
                </div>
            </div>
            <div class="col">

                @Html.LabelFor(model => model.ProductList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ProductID, new SelectList(Model.ProductList, "ProductID", "ProductName", "Select Product"))
                </div>
            </div>

            <div class="col">
                @Html.LabelFor(model => model.ProcessList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ProcessID, new SelectList(Model.ProcessList, "ProcessID", "ProcessName", "Select Process"))
                </div>
            </div>

            <div class="col">
                @Html.LabelFor(model => model.BatchList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.BatchID, new SelectList(Model.BatchList, "BatchID", "BatchName", "Select Batch"))
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                @Html.LabelFor(model => model.IssueList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @foreach (var issue in Model.IssueList)
                    {
                        <label class="font-weight-bold" for="issue_@issue.IssueID">@issue.IssueName</label>
                        <input type="checkbox" name="SelectedIssues" id="issue_@issue.IssueID" value="@issue.IssueID" class="selector">
                    }
                </div>


            </div>
        </div>
    </div>

    <div>
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Cancel", "Index", "Data", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>

<div id="formTemplate" style="display:none;">

</div>
}

onTrax-master/onTrax/Areas/Admin/Views/Data/Update.cshtml
@model onTrax.ViewModels.UpdateDataViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4 style="color:red">Update Production</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Production.ProductionID)
    @Html.HiddenFor(model => model.Production.StartTime)
    @Html.HiddenFor(model => model.Production.EndTime)
    @Html.HiddenFor(model => model.Production.DateRecorded)
    @Html.HiddenFor(model => model.Production.Product.ProductName)
    @Html.HiddenFor(model => model.Production.Process.ProcessName)
    @Html.HiddenFor(model => model.Production.Batch.BatchName)
    @Html.HiddenFor(model => model.Production.Employee.EmployeeName)


    <div class="container">
        <div class="row form-group">
            <div class="col">
                @Html.LabelFor(model => model.Production.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.Production.Duration, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Production.Duration, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col">
                @Html.LabelFor(model => model.Production.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div>
                    @Html.EditorFor(model => model.Production.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Production.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                @Html.LabelFor(model => model.Production.Employee, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Production.Employee.EmployeeID, new SelectList(Model.EmployeeList, "EmployeeID", "EmployeeName", Model.Production.Employee.EmployeeID))
                </div>
            </div>
            <div class="col">

                @Html.LabelFor(model => model.Production.Product, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Production.Product.ProductID, new SelectList(Model.ProductList, "ProductID", "ProductName", Model.Production.Product.ProductID))
                </div>
            </div>

            <div class="col">
                @Html.LabelFor(model => model.Production.Process, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Production.Process.ProcessID, new SelectList(Model.ProcessList, "ProcessID", "ProcessName", Model.Production.Process.ProcessID))
                </div>
            </div>

            <div class="col">
                @Html.LabelFor(model => model.Production.Batch, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Production.Batch.BatchID, new SelectList(Model.BatchList, "BatchID", "BatchName", Model.Production.Batch.BatchID))
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col">
                @Html.LabelFor(model => model.Production.Issues, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @foreach (var issue in Model.IssueList)
                    {
                        <label class="font-weight-bold" for="issue_@issue.IssueID">@issue.IssueName</label>
                        if (Model.Production.Issues.Where(x => x.IssueID == issue.IssueID).FirstOrDefault() != null)
                        {

                            <input type="checkbox" name="SelectedIssues" id="issue_@issue.IssueID" value="@issue.IssueID" class="selector" checked>
                        }
                        else
                        {

                            <input type="checkbox" name="SelectedIssues" id="issue_@issue.IssueID" value="@issue.IssueID" class="selector">
                        }
                    }
                </div>


            </div>
        </div>
    </div>

    <div>
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Cancel", "Edit", "Data", null, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}